version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: prueba-mysql
    environment:
      MYSQL_DATABASE: PruebaJava
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL","mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  productos-service:
    build:
      context: ./productos-service
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/PruebaJava
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      SECURITY_API-KEY_VALUE: productos-service-api-key-2025
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy

  inventario-service:
    build:
      context: ./inventario-service
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/PruebaJava
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      SECURITY_API-KEY_VALUE: inventario-service-api-key-2025
      SERVICIOS_PRODUCTOS_API-KEY: productos-service-api-key-2025
      SERVICIOS_PRODUCTOS_URL: http://productos-service:8081
    ports:
      - "8082:8082"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql-data:
